daftar_favorit/urls.py
from django.urls import path
from . import views
import datetime
from django.urls import register_converter
from .views import daftar_favorit_view, detail_daftar_favorit, insert_dummy, delete_daftar_favorit_tayangan
from .views import delete_daftar_favorit
app_name = 'daftar_favorit'

'''
to_python : convert string into datetime
to_url : convert datetime into string
'''
class TimestampConverter:
    regex = r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'  # YYYY-MM-DD HH:mm:ss

    def to_python(self, value):
        return datetime.datetime.strptime(value, '%Y-%m-%d %H:%M:%S')

    def to_url(self, value):
        return value.strftime('%Y-%m-%d %H:%M:%S')

register_converter(TimestampConverter, 'timestamp')

urlpatterns = [
    path('', daftar_favorit_view, name='daftar-favorit'),
    path('detail/<str:daftar_favorit>/<timestamp:timestamp>', detail_daftar_favorit, name='detail-daftar-favorit'),
    path('insert-dummy', insert_dummy, name='insert-dummy'),
    path('delete/<str:daftar_favorit>/<uuid:tayangan>/<timestamp:timestamp>', delete_daftar_favorit_tayangan, name='delete-tayangan-daftar-favorit'),
    path('<timestamp:timestamp>', delete_daftar_favorit, name='delete-daftar-favorit'),
]

main/urls.py
from django.urls import path
import main.views as views
from .views import landing_view
from .views import daftar_kontributor_view
from .views import kelola_langganan_view
from .views import beli_paket_view

app_name = 'main'

urlpatterns = [
    path('', views.show_main, name='show_main'),
    path('landing/', landing_view, name='landing'),
    # path('unduhan/', views.unduhan_view, name='daftar-unduhan'),
    # path('daftar-favorit/', views.daftar_favorit_view, name='daftar-favorit'),
    path('daftar-kontributor/', views.daftar_kontributor_view, name='daftar_kontributor'),
    path('langganan/', views.kelola_langganan_view, name='kelola_langganan'),
    path('beli-paket/<str:package_name>/', views.beli_paket_view, name='beli_paket'),
    path('add-transaction/<str:package_name>/', views.add_transaction, name='add_transaction'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('tayangan.urls')),
    path("daftar-kontributor/", include('daftar_kontributor.urls')),
    path("langganan/", include('langganan.urls')),
    path("daftar-favorit/", include('daftar_favorit.urls')),
    path("daftar-unduhan/", include('daftar_unduhan.urls')),
    path("auth/", include("authentication.urls"))
]

urlpatterns += staticfiles_urlpatterns()

daftar_favorit/models.py
from django.db import models

# Create your models here.

daftar_favorit/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from collections import namedtuple
import psycopg2
from psycopg2 import Error
from psycopg2.extras import RealDictCursor
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse


try:
    connection = psycopg2.connect(user= "postgres.asxvaofubgqrgynnfkho",
                        password="pacilflixE14",
                        host="aws-0-ap-southeast-1.pooler.supabase.com",
                        port="6543",
                        database="postgres")

    # Create a cursor to perform database operations
    connection.autocommit = True
    cursor = connection.cursor()
except (Exception, Error) as error:
    print("Error while connecting to PostgreSQL", error)

def map_cursor(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple("Result", [col[0] for col in desc])
    return [dict(row) for row in cursor.fetchall()]

def query(query_str: str):
    hasil = []
    with connection.cursor(cursor_factory=RealDictCursor) as cursor:
        cursor.execute("SET SEARCH_PATH TO PUBLIC")
        try:
            cursor.execute(query_str)

            if query_str.strip().upper().startswith("SELECT"):
                # Kalau ga error, return hasil SELECT
                hasil = map_cursor(cursor)
            else:
                # Kalau ga error, return jumlah row yang termodifikasi oleh INSERT, UPDATE, DELETE
                hasil = cursor.rowcount
                connection.commit()
        except Exception as e:
            # Ga tau error apa
            hasil = e

    return hasil

# Create your views here.
def daftar_favorit_view(request):
    user = request.session["username"]
    query_str = f"SELECT * FROM daftar_favorit WHERE username = '{user}'"
    hasil = query(query_str)
    context = {
        "user" : user,
        "hasil" : hasil,
    }

    return render(request, 'daftar-favorit.html', context)

def detail_daftar_favorit(request, daftar_favorit,timestamp):
    print("halo3")
    user = request.session["username"]
    query_str = f"""SELECT t.judul, tdf.timestamp, t.id FROM tayangan_memiliki_daftar_favorit tdf, 
                    tayangan t WHERE tdf.timestamp = '{timestamp}' 
                    and tdf.username = '{user}' and t.id = tdf.id_tayangan"""
    hasil = query(query_str)
    context = {
        "hasil" : hasil,
        "nama_daftar" : daftar_favorit,
    }
    return render (request, 'detail-daftar-favorit.html', context)

"""
Masih ada yang kurang
"""
def delete_daftar_favorit_tayangan(request, daftar_favorit, tayangan, timestamp):
    print("halo1")
    user = request.session["username"]
    query_str = f"""DELETE FROM tayangan_memiliki_daftar_favorit 
                    WHERE id_tayangan = '{tayangan}' 
                    AND timestamp = '{timestamp}' AND username = '{user}';"""
    hasil=query(query_str)
    print(hasil)
    return HttpResponseRedirect(reverse('daftar_favorit:detail-daftar-favorit',kwargs={'daftar_favorit': daftar_favorit, 'timestamp':timestamp }))

def delete_daftar_favorit(request, timestamp):
    print("halo")
    user = request.session["username"]
    query_str = f"""DELETE FROM daftar_favorit 
                    WHERE timestamp = '{timestamp}' 
                    AND username ='{user}';"""
    hasil = query(query_str)
    print(hasil)
    return HttpResponseRedirect(reverse('daftar_favorit:daftar-favorit'))

    

def insert_dummy(request):
    query_str = f"""INSERT INTO daftar_favorit 
    VALUES('2024-04-21 23:07:00', 'dustybun', 
    'Daftar Favorit 17');"""
    hasil = query(query_str)
    print(hasil)

daftar_favorit/templates/daftar-favorit.html
{% extends 'base.html' %}

{% block content %}
<div class="container " style="justify-content: center; text-align: center;">
    <h1>Daftar Favorit</h1>
</div>

<div class="container mx-auto px-1 py-1 background-color-blue"  >
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="text-center">Daftar Favorit</th>
                <th class="text-center">Waktu Ditambahkan</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for daftarfavorit in hasil %}
            <tr>
                <td>
                    <a href="{% url 'daftar_favorit:detail-daftar-favorit' daftar_favorit=daftarfavorit.judul timestamp=daftarfavorit.timestamp %}">
                        {{ daftarfavorit.judul }}</a>
                </td>
                <td class="text-center">{{ daftarfavorit.timestamp }}</td>
                <td class="text-center">
                    <a href="{% url 'daftar_favorit:delete-daftar-favorit' daftarfavorit.timestamp %}">
                        <button type="button" class="btn btn-danger">
                            Delete
                        </button>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

daftar_favorit/templates/detail-daftar-favorit.html
{% extends 'base.html' %}

{% block content %}
<div class="container " style="justify-content: center; text-align: center;">
    <h1>{{ nama_daftar }}</h1>
</div>

<div class="container mx-auto px-1 py-1 background-color-blue"  >
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="text-center">Judul</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for daftarfavorit in hasil %}
            <tr>
                <td>{{ daftarfavorit.judul }}</td>
                <td class="text-center">
                    <a href="{% url 'daftar_favorit:delete-tayangan-daftar-favorit' tayangan=daftarfavorit.id daftar_favorit=nama_daftar timestamp=daftarfavorit.timestamp %}">
                        <button type="button" class="btn btn-danger">
                            Delete
                        </button>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}