daftar_unduhan/urls.py
from django.urls import path
from . import views
from .views import daftar_unduhan_view,insert_dummy,delete_unduhan

app_name = 'daftar_unduhan'

urlpatterns = [
    path('', daftar_unduhan_view, name='daftar-unduhan'),
    path('insert-dummy', insert_dummy, name='insert-dummy'),
    path('delete/<uuid:id>/<timestamp:timestamp>', delete_unduhan, name='delete-unduhan')
]

main/urls.py
from django.urls import path
import main.views as views
from .views import landing_view
from .views import daftar_kontributor_view
from .views import kelola_langganan_view
from .views import beli_paket_view

app_name = 'main'

urlpatterns = [
    path('', views.show_main, name='show_main'),
    path('landing/', landing_view, name='landing'),
    # path('unduhan/', views.unduhan_view, name='daftar-unduhan'),
    # path('daftar-favorit/', views.daftar_favorit_view, name='daftar-favorit'),
    path('daftar-kontributor/', views.daftar_kontributor_view, name='daftar_kontributor'),
    path('langganan/', views.kelola_langganan_view, name='kelola_langganan'),
    path('beli-paket/<str:package_name>/', views.beli_paket_view, name='beli_paket'),
    path('add-transaction/<str:package_name>/', views.add_transaction, name='add_transaction'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('tayangan.urls')),
    path("daftar-kontributor/", include('daftar_kontributor.urls')),
    path("langganan/", include('langganan.urls')),
    path("daftar-favorit/", include('daftar_favorit.urls')),
    path("daftar-unduhan/", include('daftar_unduhan.urls')),
    path("auth/", include("authentication.urls"))
]

urlpatterns += staticfiles_urlpatterns()

tayangan/urls.py
from django.urls import path
import tayangan.views as views

app_name = 'tayangan'

urlpatterns = [
    path('trailer-tayangan/', views.show_trailer, name='show_trailer'),
    path('daftar-tayangan/', views.show_tayangan, name='show_tayangan'),
    path('search/', views.show_search, name='show_search'),
    path('film/<str:id>', views.show_film, name='show_film'),
    path('series/<str:id>', views.show_series, name='show_series'),
    path('episode/<str:id>', views.show_episode, name='show_episode'),
    path('unduh/<str:id>', views.add_unduh, name='add-unduhan'),
    path('add-to-favorit/<uuid:id>', views.add_to_favorit, name='add-to-favorit' ),

    path('api/tayangan/popular', views.get_popular_tayangan, name='get_popular_tayangan'),
    path('api/tayangan/search', views.search_tayangan, name='search_tayangan'),
    path('api/film', views.get_all_films, name='get_all_films'),
    path('api/series', views.get_all_series, name='get_all_series'),
    path('api/film/<str:id>', views.get_film_detail, name='get_film_detail'),
    path('api/series/<str:id>', views.get_series_detail, name='get_series_detail'),
    path('api/series/<str:id_series>/episode/<str:subjudul>', views.get_series_episode, name='get_series_episode'),
    path('api/tayangan/tonton', views.tonton_tayangan, name='tonton_tayangan'),
    
    path('api/ulasan', views.create_ulasan, name='create_ulasan'),
    path('api/ulasan/<str:tayangan_id>', views.get_ulasan, name='get_ulasan'),
]

tayangan/models.py
from django.db import models

# Create your models here.

tayangan/views.py
import tayangan.queries as queries
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_POST, require_GET
from datetime import datetime, timedelta
import json
from django.views.decorators.csrf import csrf_exempt
import psycopg2
from psycopg2.extras import RealDictCursor
from collections import namedtuple
from psycopg2 import Error
from django.http import JsonResponse
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.utils.timezone import make_aware
from dateutil import parser
from django.db import connection
from tayangan.database_manager import dict_fetchall, dict_fetchone


# Create your views here.
try:
    connection_psycopg = psycopg2.connect(user= "postgres.asxvaofubgqrgynnfkho",
                        password="pacilflixE14",
                        host="aws-0-ap-southeast-1.pooler.supabase.com",
                        port="6543",
                        database="postgres")

    # Create a cursor to perform database operations
    connection_psycopg.autocommit = True
    cursor = connection_psycopg.cursor()
except (Exception, Error) as error:
    print("Error while connecting to PostgreSQL", error)

def map_cursor(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple("Result", [col[0] for col in desc])
    return [dict(row) for row in cursor.fetchall()]

def query(query_str: str):
    hasil = []
    with connection_psycopg.cursor(cursor_factory=RealDictCursor) as cursor:
        cursor.execute("SET SEARCH_PATH TO PUBLIC")
        try:
            cursor.execute(query_str)

            if query_str.strip().upper().startswith("SELECT"):
                # Kalau ga error, return hasil SELECT
                hasil = map_cursor(cursor)
            else:
                # Kalau ga error, return jumlah row yang termodifikasi oleh INSERT, UPDATE, DELETE
                hasil = cursor.rowcount
                connection_psycopg.commit()
        except Exception as e:
            # Ga tau error apa
            hasil = e

    return hasil


# @csrf_exempt
# def your_view_function(request):
#     if request.method == 'POST':
#         selected_value = request.POST.get('selected')
#         # Perform your operations here
#         user = request.session["username"]
#         query_str = f"""INSERT INTO daftar_favorit VALUES('', '{user}', )"""
#         if success:
#             return JsonResponse({'status': 'success'})
#         else:
#             return JsonResponse({'status': 'error', 'message': 'An error occurred'})
#     return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

def add_unduh(request,id):
    dot_index = id.find('.')
    id_convert = id[:dot_index]
    user = request.session["username"]
    datetime_now = datetime.now()
    timestamp = datetime_now.timestamp()
    timestamp_object = datetime.fromtimestamp(timestamp)
    formatted_timestamp = timestamp_object.strftime("%Y-%m-%d %H:%M:%S")
    query_str = f"""INSERT INTO tayangan_terunduh VALUES 
        ( '{id}', '{user}', '{formatted_timestamp}');"""
    hasil = query(query_str)

    return JsonResponse({'status': 'success'})

def add_to_favorit(request,id):
    user=request.session["username"]
    if request.method == 'POST':
        selected_value = request.POST.get('pilihan_daftar_favorit')
        
        if selected_value:
            date_obj = parser.parse(selected_value)
            formatted_timestamp = date_obj.strftime("%Y-%m-%d %H:%M:%S")
           
            query_str = f"""INSERT INTO tayangan_memiliki_daftar_favorit 
            VALUES ('{id}', '{formatted_timestamp}', '{user}');"""
            hasil = query(query_str)
     
            return JsonResponse({'status': 'success'})
        

@require_GET
def show_trailer(request):
    return render(request, 'daftar_trailer.html')


@require_GET
def show_tayangan(request):
    return render(request, 'daftar_tayangan.html')


@require_GET
def show_search(request):
    return render(request, 'search_tayangan.html')


@require_GET
def show_film(request, id):
    user = request.session["username"]
    query_str = f"SELECT * FROM daftar_favorit WHERE username = '{user}'"
    hasil = query(query_str)
    
    query_str2 = f"SELECT * FROM daftar_unduhan WHERE usernam  = '{user}'"
    hasil2 = query(query_str2)
    
    dot_index = id.find('.')
    id_convert = id[:dot_index]
    
    context = {
        "user" : user,
        "hasil" : hasil,
        "unduhan": hasil2,
        "id_tayangan" : id_convert,
    }
    return render(request, 'film.html', context)


@require_GET
def show_series(request, id):
    user = request.session["username"]
    query_str = f"SELECT * FROM daftar_favorit WHERE username = '{user}'"
    hasil = query(query_str)
    
    dot_index = id.find('.')
    id_convert = id[:dot_index]
    
    context = {
        "user" : user,
        "hasil" : hasil,
        "id_tayangan" : id_convert,
    }
    return render(request, 'series.html', context)


@require_GET
def show_episode(request, id):
    return render(request, 'episode.html')


# Backend API

@require_GET
def get_popular_tayangan(request):
    try:
        cursor = connection.cursor()
        cursor.execute(queries.GET_POPULAR_TAYANGAN)
        tayangan = []
        for (i, row) in enumerate(dict_fetchall(cursor)):
            row = dict(row)
            row['peringkat'] = i + 1
            tayangan.append(row)
        cursor.close()
        return JsonResponse(tayangan, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@require_GET
def get_all_films(request):
    try:
        cursor = connection.cursor()
        cursor.execute(
            'SELECT * FROM TAYANGAN WHERE id IN (SELECT id_tayangan FROM FILM);')
        films = dict_fetchall(cursor)
        cursor.close()
        return JsonResponse(films, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@require_GET
def get_all_series(request):
    try:
        cursor = connection.cursor()
        cursor.execute(
            'SELECT * FROM TAYANGAN WHERE id IN (SELECT id_tayangan FROM SERIES);')
        series = dict_fetchall(cursor)
        cursor.close()
        return JsonResponse(series, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@require_GET
def search_tayangan(request):
    try:
        cursor = connection.cursor()
        keyword = request.GET.get('keyword', '')
        cursor.execute(queries.GET_SEARCH_TAYANGAN, {
                       'keyword': f'%{keyword}%', })
        tayangan = dict_fetchall(cursor)
        cursor.close()
        return JsonResponse(tayangan, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@require_GET
def get_film_detail(request, id):
    try:
        cursor = connection.cursor()
        cursor.execute(queries.GET_FILM_DETAIL, (id,))
        film = dict_fetchone(cursor)
        cursor.execute(queries.GET_SUTRADARA_BY_ID,
                       (film.pop('id_sutradara'),))
        film['sutradara'] = dict_fetchone(cursor)
        cursor.execute(queries.GET_GENRE_BY_TAYANGAN_ID, (id,))
        film['genres'] = dict_fetchall(cursor)
        cursor.execute(queries.GET_PEMAIN_BY_TAYANGAN_ID, (id,))
        film['pemain'] = dict_fetchall(cursor)
        cursor.execute(queries.GET_PENULIS_SKENARIO_BY_TAYANGAN_ID, (id,))
        film['penulis_skenario'] = dict_fetchall(cursor)
        cursor.close()
        return JsonResponse(film, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@require_GET
def get_series_detail(request, id):
    try:
        cursor = connection.cursor()
        cursor.execute(queries.GET_SERIES_DETAIL, (id,))
        series = dict_fetchone(cursor)
        cursor.execute(queries.GET_EPISODE_BY_SERIES_ID, (id,))
        series['episodes'] = dict_fetchall(cursor)
        cursor.execute(queries.GET_SUTRADARA_BY_ID,
                       (series.pop('id_sutradara'),))
        series['sutradara'] = dict_fetchone(cursor)
        cursor.execute(queries.GET_GENRE_BY_TAYANGAN_ID, (id,))
        series['genres'] = dict_fetchall(cursor)
        cursor.execute(queries.GET_PEMAIN_BY_TAYANGAN_ID, (id,))
        series['pemain'] = dict_fetchall(cursor)
        cursor.execute(queries.GET_PENULIS_SKENARIO_BY_TAYANGAN_ID, (id,))
        series['penulis_skenario'] = dict_fetchall(cursor)
        cursor.close()
        return JsonResponse(series, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@require_GET
def get_series_episode(request, id_series, subjudul):
    try:
        cursor = connection.cursor()
        subjudul = subjudul.replace('_', ' ')
        cursor.execute(queries.GET_EPISODE_BY_ID, (id_series, subjudul))
        episode = dict_fetchone(cursor)
        cursor.execute(queries.GET_OTHER_EPISODES, (id_series, subjudul))
        episode['other_episodes'] = dict_fetchall(cursor)
        cursor.close()
        return JsonResponse(episode, safe=False)
    except Exception as e:
        connection.rollback()
        return JsonResponse({'message': str(e)})


@csrf_exempt
@require_POST
def tonton_tayangan(request):
    cursor = connection.cursor()
    try:
        if 'username' not in request.session:
            return JsonResponse({'status': 'failed', 'message': 'User not authenticated'}, status=401)
        username = request.session.get('username')
        json_data = json.loads(request.body)
        id_tayangan = json_data.get('id_tayangan')
        progress_percentage = json_data.get('progress_percentage')

        cursor.execute(queries.GET_DURASI_TAYANGAN, {'id': id_tayangan})

tayangan/templates/daftar_tayangan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="container-lg">
  <h1 class="my-4">Daftar Tayangan</h1>

  <form class="d-flex my-4" role="search">
    <input id="search-bar" class="form-control me-2" type="search" placeholder="Cari tayangan berdasarkan judul..."
      aria-label="Search">
    <button id="search-button" class="btn btn-outline-success" type="submit">Search</button>
  </form>

  <section class="my-4">
    <h2>10 Tayangan Terbaik Minggu ini</h2>
    <table class="table  table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Peringkat</th>
          <th scope="col">Judul</th>
          <th scope="col">Sinopsis Trailer</th>
          <th scope="col">URL Trailer</th>
          <th scope="col">Tanggal Rilis Trailer</th>
          <th scope="col">Total View (7 hari terakhir)</th>
          <th scope="col">Tayangan</th>
        </tr>
      </thead>
      <tbody id="tayangan-terbaik-tbody" class="table-group-divider"></tbody>
    </table>
  </section>


  <section class="my-4">
    <h2>Film</h2>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Judul</th>
          <th scope="col">Sinopsis Trailer</th>
          <th scope="col">URL Trailer</th>
          <th scope="col">Tanggal Rilis Trailer</th>
          <th scope="col">Tayangan</th>
        </tr>
      </thead>
      <tbody id="film-tbody" class="table-group-divider">
        
    </table>
  </section>


  <section class="my-4">
    <h2>Series</h2>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Judul</th>
          <th scope="col">Sinopsis Trailer</th>
          <th scope="col">URL Trailer</th>
          <th scope="col">Tanggal Rilis Trailer</th>
          <th scope="col">Tayangan</th>
        </tr>
      </thead>
      <tbody id="series-tbody" class="table-group-divider">
        <tr>
          <td>Mark 1</td>
          <td>Lorem ipsum dolor sit amet consectetur adipisicing elit.</td>
          <td><a href="www.example.com">www.example.com</a></td>
          <td>1 Januari 2020</td>
          <td><a href="/series/abcde" type="button" class="btn btn-dark">View More</a></td>
        </tr>
    </table>
  </section>

</main>

<script type="module" src="{% static 'js/daftar_tayangan.js' %}"></script>
{% endblock content %}

tayangan/templates/daftar_trailer.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="container-lg">
  <h1 class="my-4">Daftar Tayangan</h1>

  <form class="d-flex my-4" role="search">
    <input id="search-bar" class="form-control me-2" type="search" placeholder="Cari tayangan berdasarkan judul..."
      aria-label="Search">
    <button id="search-button" class="btn btn-outline-success" type="submit">Search</button>
  </form>

  <section class="my-4">
    <h2>10 Tayangan Terbaik Minggu ini</h2>
    <table class="table  table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Peringkat</th>
          <th scope="col">Judul</th>
          <th scope="col">Sinopsis Trailer</th>
          <th scope="col">URL Trailer</th>
          <th scope="col">Tanggal Rilis Trailer</th>
          <th scope="col">Total View (7 hari terakhir)</th>
        </tr>
      </thead>
      <tbody id="tayangan-terbaik-tbody" class="table-group-divider"></tbody>
    </table>
  </section>


  <section class="my-4">
    <h2>Film</h2>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Judul</th>
          <th scope="col">Sinopsis Trailer</th>
          <th scope="col">URL Trailer</th>
          <th scope="col">Tanggal Rilis Trailer</th>
        </tr>
      </thead>
      <tbody id="film-tbody" class="table-group-divider"></tbody>
    </table>
  </section>


  <section class="my-4">
    <h2>Series</h2>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Judul</th>
          <th scope="col">Sinopsis Trailer</th>
          <th scope="col">URL Trailer</th>
          <th scope="col">Tanggal Rilis Trailer</th>
        </tr>
      </thead>
      <tbody id="series-tbody" class="table-group-divider"></tbody>
    </table>
  </section>

</main>

<script src="{% static 'js/daftar_trailer.js' %}"></script>
{% endblock content %}

tayangan/templates/film.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



<main class="container-lg">
  {% include 'modal-favorit.html' %}
  {% include 'modal-unduh.html' %}
  <h1 id="judul" class="mb-4">Judul</h1>

  <div class="d-flex flex-row justify-content-center my-4">
    <input type="range" name="progress-tonton" id="progress-input" min="0" max="100" value="0" class="w-50">
    <p class="inline my-auto mx-2">
      <span id="progress-percentage">0</span>%
    </p>
  </div>

  <button class="btn btn-primary" type="submit" id="tonton-button">Tonton</button>
  <a href="{% url 'tayangan:add-unduhan' id_tayangan %}">
    <button class="btn btn-primary" type="submit" data-bs-toggle="modal" data-bs-target="#ModalUnduh">Unduh
      Film</button>
  </a>
  <button class="btn btn-primary" type="submit" data-bs-toggle="modal" data-bs-target="#ModalFavorit">Favorit
    Tayangan</button>

  <section>
    <div>
      <strong>Total view:</strong> <span id="total-view">N/A</span>
    </div>
    <div>
      <strong>Rating rata-rata:</strong> <span id="rating">N/A</span>/5
    </div>
    <div>
      <strong>Durasi film:</strong> <span id="durasi-film">N/A</span> menit
    </div>
    <div>
      <strong>Tanggal rilis:</strong> <span id="release-date-film">N/A</span>
    </div>
    <div>
      <strong>URL Film:</strong> <a id="url-video-film" href="#">N/A</a>
    </div>
    <div>
      <strong>Asal negara:</strong> <span id="asal-negara">N/A</span>
    </div>
    <div>
      <strong>Sinopsis:</strong>
      <p id="sinopsis">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam facilisis libero nec
        mi commodo, vel rutrum neque eleifend. Vivamus nec turpis nec quam gravida faucibus.
      </p>
    </div>
    <div><strong>Genre:</strong> <span id="genre">N/A</span></div>
  </section>

  <section>
    <div>
      <strong>Pemain: </strong>
      <div id="pemain">
        N/A
      </div>
    </div>
    <div>
      <strong>Penulis skenario: </strong>
      <div id="penulis-skenario">
        N/A
      </div>
    </div>
    <div>
      <strong>Sutradara: </strong>
      <a id="sutradara" href="#">N/A</a>
    </div>
  </section>

  <input type="hidden" name="tayangan_id" id="tayangan-id">

  <div id="liveAlertPlaceholder" class="position-fixed bottom-0 end-0 z-3"></div>

  {% include 'ulasan.html' %}

</main>

<script src="{% static 'js/film.js' %}" type="module"></script>
<script src="{% static 'js/tonton_tayangan.js' %}" type="module"></script>
{% endblock content %}

tayangan/templates/modal-favorit.html
<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .dropdown-menu {
      max-height: 200px;
      overflow-y: auto;
    }

    .modal-body {
      display: flex;
      flex-direction: column;
      flex-wrap: wrap;
      max-height: 400px;
    }

    .modal-content {
      display: flex;
      flex-direction: column;
      flex-wrap: wrap;
      max-height: 400px;
    }

    .modal-dialog {
      display: flex;
      flex-direction: column;
      flex-wrap: wrap;
      max-height: 400px;
      max-width: 800px;
    }
  </style>
</head>
<body>
  <div class="modal fade" id="ModalFavorit" tabindex="-1" aria-labelledby="ModalFavorit" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="container mx-auto">
            <h1 class="modal-title fs-5" style="justify-content: center; text-align: center;">Masukkan ke Daftar Favorit</h1>
          </div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" style="justify-content: center; text-align: center;">
          <form action="{% url 'tayangan:add-to-favorit' id_tayangan %}" method="post">
            {% csrf_token %}
            
            <!-- Dropdown list for selecting a song -->
            <select id="pilihan_daftar_favorit" name="pilihan_daftar_favorit" required>
              <!-- Iterate through all songs and create an option for each one -->
              {% for daftarfavorit in hasil %}
                  <option value="{{ daftarfavorit.timestamp }}">
                      {{ daftarfavorit.judul }}
                  </option>
              {% endfor %}
            </select><br><br>
    
            <!-- Submit button -->
            <button type="submit" class="btn btn-primary mt-3" data-bs-dismiss="modal">SUBMIT</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    const dropdownElementList = document.querySelectorAll('.dropdown-toggle');
    const dropdownList = [...dropdownElementList].map(dropdownToggleEl => new bootstrap.Dropdown(dropdownToggleEl));

    let selectedValue = null;

    const saveButton = document.getElementById('saveButton');
    const dropdownMenu = document.getElementById('dropdownMenu');

    dropdownMenu.addEventListener('click', (event) => {
      if (event.target.classList.contains('dropdown-item')) {
        selectedValue = event.target.textContent;
      }
    });

    saveButton.addEventListener('click', () => {
      if (selectedValue) {
        console.log('Selected value:', selectedValue);
        // Do something with the selected value, e.g., send it to the server
      } else {
        console.log('No item selected');
      }
    });
  </script>
</body>
</html>

tayangan/templates/modal-unduh.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<div id="modalContainer"></div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script>
  const modalContainer = document.getElementById("modalContainer");
  const judul = document.getElementById('judul').innerText;
  // Define the modal HTML as a string
  const modalHTML = `
  <div class="m-2 text-black d-flex flex-column align-items-center justify-content-center">
    <div class="modal fade" id="ModalUnduh" tabindex="-1" aria-labelledby="ModalUnduh" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Unduh</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
                <div class="modal-body" style="white-space: normal;">
                  <p>Selamat! Anda telah berhasil mengunduh '${judul}' dan akan berlaku hingga 09/05/2024. Cek informasi selengkapnya pada halaman daftar unduhan.</p>
                </div>          
              <div class="modal-footer">
                  <a href="{% url 'daftar_unduhan:daftar-unduhan' %}">
                      <button type="button" class="btn btn-primary">
                          Cek Daftar Unduhan
                      </button>
                  </a>
                  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
              </div>
          </div>
      </div>
    </div>
  </div>`;

  // Set the innerHTML of the modal container element to the modal HTML string
  modalContainer.innerHTML = modalHTML;

  
  </script>
  

tayangan/templates/series.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="container-lg">
  <h1 id="judul">Judul</h1>

  <section>
    <h2>Episode</h2>
    <div id="episode">
      N/A
    </div>
  </section>
  {% include 'modal-favorit.html' %}
  {% include 'modal-unduh.html' %}

  
  <a href="{% url 'tayangan:add-unduhan' id_tayangan %}">
    <button class="btn btn-primary" type="submit" data-bs-toggle="modal" data-bs-target="#ModalUnduh">Unduh Series</button>
  </a>
  <button class="btn btn-primary" type="submit" data-bs-toggle="modal" data-bs-target="#ModalFavorit">Tambahkan ke Favorit</button>

  <section>
    <div>
      <strong>Total view:</strong> <span id="total-view">N/A</span>
    </div>
    <div>
      <strong>Rating rata-rata:</strong> <span id="rating">N/A</span>/5
    </div>
    <div>
      <strong>Asal negara:</strong> <span id="asal-negara">N/A</span>
    </div>
    <div>
      <strong>Sinopsis:</strong>
      <p id="sinopsis">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam facilisis libero nec
        mi commodo, vel rutrum neque eleifend. Vivamus nec turpis nec quam gravida faucibus.
      </p>
    </div>
    <div><strong>Genre:</strong> <span id="genre">N/A</span></div>
  </section>

  <section>
    <div>
      <strong>Pemeran: </strong>
      <div id="pemain">
        N/A
      </div>
    </div>
    <div>
      <strong>Penulis Naskah:</strong>
      <div id="penulis-skenario">
        N/A
      </div>
    </div>
    <div>
      <strong>Sutradara: </strong>
      <a id="sutradara" href="#">N/A</a>
    </div>
  </section>

  {% include 'ulasan.html' %}

</main>

<script src="{% static 'js/series.js' %}" type="module"></script>
{% endblock content %}